version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: shortlink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  shortlink-service:
    container_name: shortlink-base-service
    build: shortlink-base-service/
    image: shortlink-base-service-image
    depends_on:
      - authentication-service
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    restart: always

  authentication-service:
    container_name: shortlink-authentication-service
    build: shortlink-authentication-service/
    image: shortlink-authentication-service-image
    ports:
      - 8081:8081
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
      - postgres
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./sidecar/prometheus-config.yaml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus


  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./sidecar/grafana-config.yaml:/etc/grafana/provisioning/config.yaml
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  prometheus:
  grafana:
