server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/shortlink
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

securityEnabled: false


