server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shortlink
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres


securityEnabled: true
