server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/shortlink
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml

expirationMinutes: 1